#!/usr/bin/env bash
#:Usage: cornora [-tl cmd] [-tr cmd] [-bl cmd] [-br cmd] [-v]
#:
#:  cmd:   run the command when mouse reach to the edge of screen:
#:
#:  -tl cmd   top-left
#:  -tr cmd   top-right
#:  -bl cmd   bottom-left
#:  -br cmd   bottom-right
#:  -h        show the help
#:  -v        verbose output
#:
# same as py version before, but faster

eval $(xdotool getdisplaygeometry --shell)
G=2;MR=4 W=$((WIDTH-G)); H=$((HEIGHT-G)); DB=/tmp/cornora.lck;

usage() {
    grep "^#:" $0 | while read DOC; do printf '%s\n' "${DOC###:}"; done
    exit
}

options() {
    while [[ "$1" ]]; do
        case "$1" in
            "-tl") tl="$2" ;;
            "-tr") tr="$2" ;;
            "-bl") bl="$2" ;;
            "-br") br="$2" ;;
            "-h") usage ;;
            "-v") verbose=1 ;;
        esac
    shift
    done
}

delay() {
    local IFS
    [[ -n "${_de:-}" ]] || exec {_de}<> <(:)
    read ${1:+-t "$1"} -u $_de || :
}

invoke() {
    proc=$(IFS=" "; set -- $1; echo $1)
    id="$(pidof -x "$proc")"
    if [[ -n "$verbose" ]]; then
        [[ -z "$id" ]] && (eval "$1" &) || (kill -9 $id &)
    else
        [[ -z "$id" ]] && (eval "$1" 2&>/dev/null &) || (kill -9 $id 2&>/dev/null &)
    fi
    xdotool mousemove_relative $2 $3
    delay 0.1
}

[[ -f "$DB" && -z "$(cat $DB | xargs ps -p)" ]] && rm -rf $DB
if [[ ! -f "$DB" ]]; then
    printf "%s\n" $$ >$DB
    trap 'rm -rf "$DB"; exit $?' INT TERM EXIT
    [[ -z "$@" ]] && usage || options "$@"
    while :;do
        eval $(xdotool getmouselocation --shell)
        [[ -n "$tl" && "$X" -lt "$G" && "$Y" -lt "$G" ]] && invoke "$tl" $((X+MR)) $((Y+MR))
        [[ -n "$tr" && "$X" -gt "$W" && "$Y" -lt "$G" ]] && invoke "$tr" $((X-MR)) $((Y+MR))
        [[ -n "$bl" && "$X" -lt "$G" && "$Y" -gt "$H" ]] && invoke "$bl" $((X+MR)) $((Y-MR))
        [[ -n "$br" && "$X" -gt "$W" && "$Y" -gt "$H" ]] && invoke "$br" $((X-MR)) $((Y-MR))
        delay 0.2
    done
    rm -rf $DB
    trap - INT TERM EXIT
else    
    printf "Lock Exists: Cornora is running at PID $(cat $DB). run \"pkill -f $(basename $0)\" to close it.\n"
    exit 1
fi
